WITH CTE AS (
SELECT
    A.FLAVOR,
    A.TOTAL_ORDER + SUM(B.TOTAL_ORDER) AS TOTAL_ORDER
FROM
    FIRST_HALF AS A
JOIN
    JULY AS B USING(FLAVOR)
GROUP BY
    B.FLAVOR
ORDER BY
    TOTAL_ORDER DESC
LIMIT 3)

SELECT FLAVOR FROM CTE