SELECT
    EMPLOYEES.DEPT_ID,
    DEPARTMENT.DEPT_NAME_EN,
    ROUND(AVG(EMPLOYEES.SAL), 0) AS  AVG_SAL
FROM
    HR_EMPLOYEES AS EMPLOYEES
JOIN
    HR_DEPARTMENT AS DEPARTMENT
ON
    EMPLOYEES.DEPT_ID = DEPARTMENT.DEPT_ID
GROUP BY
    EMPLOYEES.DEPT_ID
ORDER BY
    AVG_SAL DESC