SELECT
    PRICE_GROUP,
    COUNT(PRICE_GROUP) AS PRODUCTS
FROM(
    SELECT
        TRUNCATE(PRICE, -4) AS PRICE_GROUP
    FROM
        PRODUCT) AS AA
GROUP BY
    PRICE_GROUP
ORDER BY
    PRICE_GROUP
